// <auto-generated />
namespace fuzzy_octo_tribble.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class EventDataModelFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventDataModelFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201404272050350_EventDataModelFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
