// <auto-generated />
namespace fuzzy_octo_tribble.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CharacterName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CharacterName));
        
        string IMigrationMetadata.Id
        {
            get { return "201402262303000_CharacterName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
